from alpine:{{VERSION}}

run apk add alpine-sdk alpine-conf syslinux xorriso squashfs-tools \
            grub grub-efi doas mtools dosfstools grub-efi cryptsetup \
            lvm2

copy assets/*  /tmp/assets/

run sh /tmp/assets/prep.sh

run sh /tmp/assets/build-iso.sh {{VERSION}}
